& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'ColumnHeader3.Name' = 'ColumnHeader3'
'ColumnHeader1.Name' = 'ColumnHeader1'
'Button1.Name' = 'Button1'
'ListView6.Name' = 'ListView6'
'ListView3.Name' = 'ListView3'
'ColumnHeader7.Name' = 'ColumnHeader7'
'ColumnHeader10.Name' = 'ColumnHeader10'
'ListView2.Name' = 'ListView2'
'Label2.Name' = 'Label2'
'Button3.Name' = 'Button3'
'ListView5.Name' = 'ListView5'
'UpdateHistoryPanel.Name' = 'UpdateHistoryPanel'
'ColumnHeader8.Name' = 'ColumnHeader8'
'Button5.Name' = 'Button5'
'ColumnHeader9.Name' = 'ColumnHeader9'
'CheckBox1.Name' = 'CheckBox1'
'UpdateInstallationPanel.Name' = 'UpdateInstallationPanel'
'ColumnHeader6.Name' = 'ColumnHeader6'
'ColumnHeader4.Name' = 'ColumnHeader4'
'ColumnHeader5.Name' = 'ColumnHeader5'
'Label1.Name' = 'Label1'
'ListView4.Name' = 'ListView4'
'ListView1.Name' = 'ListView1'
'ListView7.Name' = 'ListView7'
'$this.Name' = 'Form1'
'ColumnHeader2.Name' = 'ColumnHeader2'
'Button4.Name' = 'Button4'
'Button2.Name' = 'Button2'
}
}